### PR TITLE
Fixed issue #20: Removed \n from readmore.template.html which adds an…

### PR DESCRIPTION
**Pull request by bgsavage**
… extra space when "more lands on a word"

Added gulp-frep because my gulp was adding \r\n wherever \n was present - not sure if it should be doing this?

### CODE REVIEW

**Comment by laxika** [comment]
Will this be pulled and released anytime soon?

**Comment by bgsavage** [comment]
I'm still hopeful :)

**Comment by hjmodha** [comment]
@ismarslomic Pls merge this pull request and if not appropriate then close

**Comment by ismarslomic** [comment]
Fixed in 4660d51725099dbc6bca7b5103f5128fa9ae9c5d

**Pull request closed without merging**
